version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data: